### ISSUE TITLE
Trying to compile for iphone6 but gives me 40 warnings and crashes

### ISSUE THREAD

**Issue by sriranjanr** [Soonhwan-Kwon/aurioTouch#2]
Hello,

I am trying to run your code but I get 40 warnings and the application crashes.I am using xcode 8.3.3 and iphone 6.I want to use aurio touch and I also want to record from both the mics separately. Could you help me solve my problems with warnings (and prevent the application from crashing) and how to record from the second mic. Let me know.

![auriotouch record crashes](https://user-images.githubusercontent.com/8640547/32317674-9bf7bb82-bfda-11e7-95b1-80a1eb9dab75.png)

**Comment by Soonhwan-Kwon** [comment]
Sorry it is very old project (about 5 years ago) and I expect it is not compatible for present version.

**Comment by sriranjanr** [comment]
Record and play is a very useful addition to auriotouch.I want to get this working on Iphone 6. Could you please help me in getting this to work? Also I want to record from the second mic of iphone6. Kindly help me.

**Comment by sriranjanr** [comment]
Let us start by this warning where a negative value is being shifted.
![negative signed value being shifted](https://user-images.githubusercontent.com/8640547/32318468-65d9470c-bfdd-11e7-9b30-e5880d909e47.png)

37 other warnings are deprecated warnings..
